# where input, output, and checks data go
DATA_DIR: data

# where to store figures
FIGS_DIR: analysis/figs

# paths to config files
TRUTH_PATH: config/truth.yaml
PRIOR_PATH: config/priors.yaml
NOISE_PATH: config/noise.yaml
